admin-port: 8444
application-port: 8443

application-fqdn: localhost.goth.com

app-tls-cert: ./resources/server.domain.crt
app-tls-privatekey: ./resources/server.key

admin-tls-cert: ./resources/server.domain.crt
admin-tls-privatekey: ./resources/server.key
